import subprocess
import os
import datetime
import html

class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    CYAN = '\033[96m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def save_to_html(content, report_path):
    parent_dir = os.path.dirname(report_path)
    if parent_dir and not os.path.exists(parent_dir):
        os.makedirs(parent_dir, exist_ok=True)
    
    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Network Audit - TERMINAL CLI</title>
    <style>
        body {{ background-color: #0c0c0c; color: #cccccc; font-family: 'Consolas', 'Courier New', monospace; padding: 25px; line-height: 1.5; }}
        .header {{ color: #f178f1; font-weight: bold; font-size: 1.3em; border-bottom: 2px solid #333; padding-bottom: 10px; }}
        .adapter {{ color: #3b8eea; font-weight: bold; margin-top: 25px; display: block; background: #1a1a1a; padding: 5px; border-left: 3px solid #3b8eea; }}
        .ip {{ color: #4ec9b0; }}
        .mac {{ color: #ce9178; }}
        .footer {{ color: #555; font-size: 0.8em; margin-top: 30px; border-top: 1px solid #333; padding-top: 10px; }}
        pre {{ white-space: pre-wrap; word-wrap: break-word; background: #111; padding: 10px; border-radius: 4px; }}
    </style>
</head>
<body>
    <div class="header">TERMINAL CLI - NETWORK AUDIT</div>
    <div style="font-size: 0.9em; color: #888; margin-top: 5px;">Report Date: {datetime.datetime.now().strftime('%d.%m.%Y %H:%M:%S')}</div>
    <pre>{content}</pre>
    <div class="footer">Report automatically generated by TERMINAL CLI system</div>
</body>
</html>
"""
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html_template)

def get_full_ipconfig():
    os.system('') # Activate ANSI in Windows
    report_content = ""
    target_path = os.path.expandvars(r"%userprofile%\.polsoft\psCLI\reports\network_report.html")

    print(f"{Colors.BOLD}{Colors.HEADER}--- Full TCP/IP Configuration (TERMINAL CLI) ---{Colors.ENDC}\n")

    try:
        # Attempt cp852 (Windows PL standard), fallback to utf-8 if needed
        # For English Windows, 'cp437' or 'utf-8' is usually standard
        result = subprocess.run(["ipconfig", "/all"], capture_output=True, text=True, encoding="cp852", shell=True, check=True)
        lines = result.stdout.splitlines()

        for line in lines:
            l_clean = line.strip()
            if not l_clean: 
                report_content += "\n"
                continue
            
            # Safe HTML parsing
            l_safe = html.escape(line)

            if "Karta" in line or "Adapter" in line:
                formatted_cli = f"\n>>> {l_clean}"
                print(f"{Colors.BOLD}{Colors.BLUE}{formatted_cli}{Colors.ENDC}")
                report_content += f'<span class="adapter">{l_safe}</span>'
            elif any(k in line for k in ["IPv4", "Maska", "Subnet", "Brama", "Gateway"]):
                print(f"   {Colors.GREEN}{l_clean}{Colors.ENDC}")
                report_content += f'<span class="ip">{l_safe}</span>\n'
            elif any(k in line for k in ["Physical", "Adres fizyczny", "DHCP", "Lease", "DNS"]):
                print(f"   {Colors.YELLOW}{l_clean}{Colors.ENDC}")
                report_content += f'<span class="mac">{l_safe}</span>\n'
            else:
                print(f"   {l_clean}")
                report_content += f"{l_safe}\n"

        save_to_html(report_content, target_path)
        print(f"\n{Colors.CYAN}[OK] Report saved successfully at:{Colors.ENDC}")
        print(f"{Colors.YELLOW}{target_path}{Colors.ENDC}")

    except subprocess.CalledProcessError:
        print(f"{Colors.RED}[!] Error: Failed to retrieve data from ipconfig.{Colors.ENDC}")
    except Exception as e:
        print(f"{Colors.RED}[!] Critical Error: {e}{Colors.ENDC}")

    finally:
        print("\n" + f"{Colors.BLUE}" + "-"*45 + f"{Colors.ENDC}")
        input("Press Enter to return to TERMINAL CLI...")

if __name__ == "__main__":
    get_full_ipconfig()